version: "3.7"
services:
  comics-app:
      volumes:
        - source: ./www
          target: /var/www
          type: bind
        - source: .env
          target: /var/www/.env
          type: bind
  comics-www:
      volumes:
        - source: ./www
          target: /var/www
          type: bind
  comics-adminer:
      image: adminer
      restart: unless-stopped
      labels:
          - "traefik.enable=true"
          - "traefik.frontend.priority=50"
          - "traefik.docker.network=proxy"
          - "traefik.port=8080"
          - "traefik.frontend.rule=HostRegexp: ${docker_project}-adminer.{domain:.+}"
          # Traefik v2
          - "traefik.http.routers.${docker_project}-adminer.rule=Host(`${docker_project}-adminer.app.loc`)"
          - "traefik.http.routers.${docker_project}-adminer.entrypoints=http"
      networks:
          default: {}
          intern:
              aliases:
                  - adminer
      depends_on:
          - comics-mysql